export  const
    ADD_TODO = 'ADD_TODO',
    TOGGLE_TODO = 'TOGGLE_TODO',
    EDIT_TODO = 'EDIT_TODO',
    SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',
    SAVE_TODO = 'SAVE_TODO',
    DELETE_TODO ='DELETE_TODO',
    GET_VISIBLE_TODOS = 'GET_VISIBLE_TODOS ',

    ALL = 'ALL',
    DONE = 'DONE',
    UNDONE = 'UNDONE';


