export  const
    ADD_TODO = 'ADD_TODO',
    TOGGLE_TODO = 'TOGGLE_TODO',
    EDIT_TODO = 'EDIT_TODO',
    SAVE_TODO = 'SAVE_TODO',
    DELETE_TODO ='DELETE_TODO',

    SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',

    UPLOAD_TODOS = 'UPLOAD_TODOS',

    ALL = 'ALL',
    DONE = 'DONE',
    UNDONE = 'UNDONE';


