export  const
    ADD_TODO = 'ADD_TODO',
    TOGGLE_TODO = 'TOGGLE_TODO',
    EDIT_TODO = 'EDIT_TODO',
    SAVE_TODO = 'SAVE_TODO',
    DELETE_TODO ='DELETE_TODO',

    SET_VISIBILITY_FILTER = 'SET_VISIBILITY_FILTER',

    UPLOAD_TODOS = 'UPLOAD_TODOS',
    UPLOAD_TODOS_REQUEST = 'UPLOAD_TODOS_REQUEST',
    UPLOAD_TODOS_FAILURE = 'UPLOAD_TODOS_FAILURE',
    UPLOAD_TODOS_SUCCESS = 'UPLOAD_TODOS_SUCCESS',
    UPLOAD_TODOS_NOTFETCHING = 'UPLOAD_TODOS_NOTFETCHING',


    ALL = 'ALL',
    DONE = 'DONE',
    UNDONE = 'UNDONE';


